# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{salesforce-sync}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Moritz Heidkamp", "Christof Spies"]
  s.date = %q{2010-12-02}
  s.default_executable = %q{salesforce-sync}
  s.description = %q{This gem provides a program named salesforce-sync which allows you to synchronize Salesforce objects into a local database. Currently only unidirectional synchronization from Salesforce into a local database is implemented.}
  s.email = %q{moritz@twoticketsplease.de}
  s.executables = ["salesforce-sync"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/salesforce-sync",
    "examples/config.yml",
    "lib/salesforce_sync.rb",
    "lib/salesforce_sync/database.rb",
    "lib/salesforce_sync/interactive.rb",
    "lib/salesforce_sync/salesforce.rb",
    "lib/salesforce_sync/salesforce/types.rb",
    "lib/salesforce_sync/synchronization.rb"
  ]
  s.homepage = %q{http://github.com/DerGuteMoritz/salesforce-sync}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Synchronize Salesforce objects into a local database}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-pg>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_runtime_dependency(%q<DerGuteMoritz-rforce>, ["= 4.2.0"])
      s.add_runtime_dependency(%q<activesupport>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<activerecord>, ["= 3.0.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
    else
      s.add_dependency(%q<ruby-pg>, [">= 0"])
      s.add_dependency(%q<builder>, ["~> 2.1.2"])
      s.add_dependency(%q<DerGuteMoritz-rforce>, ["= 4.2.0"])
      s.add_dependency(%q<activesupport>, ["= 3.0.3"])
      s.add_dependency(%q<activerecord>, ["= 3.0.3"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    end
  else
    s.add_dependency(%q<ruby-pg>, [">= 0"])
    s.add_dependency(%q<builder>, ["~> 2.1.2"])
    s.add_dependency(%q<DerGuteMoritz-rforce>, ["= 4.2.0"])
    s.add_dependency(%q<activesupport>, ["= 3.0.3"])
    s.add_dependency(%q<activerecord>, ["= 3.0.3"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
  end
end

