lock_file: /tmp/asd

salesforce:
  url: https://www.salesforce.com/services/Soap/u/20.0
  username: foo
  password: bar
  token: baz


database:
  connection:
    adapter: postgresql
    host: localhost
    username: postgres
    database: salesforce